name: Clojure CI

on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies
      run: make dependencies
    - name: Check outdated dependencies
      run: make outdated
    - name: Run tests
      run: make test
