name: pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  outdated-dependencies:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Setup backend environment
      uses: ./.github/actions/setup-backend
      with:
        m2-cache-key: db0-outdated

    - name: Check outdated dependencies
      run: make outdated

  testing:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Setup backend environment
      uses: ./.github/actions/setup-backend
      with:
        m2-cache-key: db0-testing

    - name: Run tests
      run: make test
