name: pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  setup-environment:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Setup backend environment
      uses: ./.github/actions/setup-environment
      with:
        m2-cache-key: db0-environment

    - name: Check outdated dependencies
      run: make outdated
      
  poly-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Setup backend environment
      uses: ./.github/actions/setup-environment
      with:
        m2-cache-key: db0-environment

    - name: Polylith check
      run: make poly-check

  testing:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Setup backend environment
      uses: ./.github/actions/setup-environment
      with:
        m2-cache-key: db0-environment

    - name: Run tests
      run: clojure -M:poly test :all :dev
